### ISSUE TITLE
do not update mhd with server provided numbers

### ISSUE THREAD

**Issue by hftl-kalle** [Explie/FridgeApp#38]
if the user scans a product and uses the server provided bestbefore date, do not add this number to the product mhd values.

**Comment by hftl-kalle** [comment]
Need to question explie about this.
Implementation depends on client input.
Maybe if MHD field is left empty the server provided number is used. another method might be to send another field with the post message that states if the mhd was modified by user or not

**Comment by hftl-kalle** [comment]
using an extra field.
userMhd : bool

**Comment by Explie** [comment]
using an extra field userMhd result in an error

fridgeContent={"amount":1,"ean":"4003273217874",
"unit":"Stück",
"category":"Haushalt, Büro",
"stats":false,
"tag":"Block",
"name":"Baier & Schneider Notizblock Collegeblock Glocken-Design, Spiralbindung, 4fach, 60 g\/qm, A4, karie",
"buyDate":"2015,12,23",
"mhd":"2016,12,23",
"userMhd":true}:

**Comment by Explie** [comment]
i am dumband tired never mind
