### ISSUE TITLE
scanned product, did not get product info

### ISSUE THREAD

**Issue by hftl-kalle** [Explie/FridgeApp#85]
scanned product which is known to the database.
was the first product ever scanned
got the add product dialog after scanning without any data provided

was unable to reproduce

**Comment by Explie** [comment]
priority: low

**Comment by hftl-kalle** [comment]
Could replicate its the very first Search after installing that does mir return a product

**Comment by Explie** [comment]
i will dive into this

**Comment by Explie** [comment]
still not able to replicate on my side, uninstalled and reinstalled several times always got the product returned on first scan

**Comment by hftl-kalle** [comment]
hmh could not reproduce this time. i'll close it for now
