### ISSUE TITLE
product information should be updated on add product if not set

### ISSUE THREAD

**Issue by Explie** [Explie/FridgeApp#89]
when scanning a product which is found in openEAN but has not set all information (e.g. Category) the category should be updated with the user data on addProduct

e.g.:
"ean": "7322540786514"
"name": "Tempo Original Taschentücher "Klassik" 15 x 10 Tücher, 10er Pack (10 x 15 Stück)"
"category": ""
"tag": ""
"unit": ""
"mhd": 122

Category,tag and unit should be set with the users data on addProduct when null

**Comment by hftl-kalle** [comment]
it should already do that
let me check
