### ISSUE TITLE
fridge array order changes on fridge-renaming

### ISSUE THREAD

**Issue by Explie** [Explie/FridgeApp#93]
when a fridge is renamed it will be set to the end of the array returned in the next get fridges request

e.g.

1: get fridges

returned in order:
+ 1.fridge abc
+ 2.fridge abcd
+ 3.fridge abcde

2: rename fridge abc to fde

3: get fridges again

returned in order:
+ 1.fridge abcd
+ 2.fridge abcde
+ 3.fridge fde

this is not the behavior the user would expect

**Comment by Explie** [comment]
i was not able to reproduce this, seems to only affect the automatic created fridge and only once

**Comment by Explie** [comment]
shouldnt be closed

**Comment by hftl-kalle** [comment]
unable to reproduce at all.
either it has something to do with the way mongodb returns the documents or it is a problem with the android app
either way i'll close it. if anybody can reproduce, reopen it and provide info
