### ISSUE TITLE
rounding issues after withdrawal

### ISSUE THREAD

**Issue by Explie** [Explie/FridgeApp#94]
"Hatte 0.7 Liter darin und habe 0.25 entfernt jetzt habe ich noch 0.44999999999999996 Liter" - from onedrive

please round amount left after withdrawal to two decimal places

**Comment by Explie** [comment]
error was submited by diana, i could not reproduce it

**Comment by hftl-kalle** [comment]
was able to reproduce.
rounded to 3 points after decimal. 
db, postman all return proper 0.45 in every situation but app displays 0.449999999....after deleting 0.25 from 0.7
after clicking on sync app displays 0.45 as well. seems to be a java floating point issue.
@Explie are you doing some calculations locally to display the content after delete or are you using the answer the server provides to refresh info?

**Comment by Explie** [comment]
meh.
most likely my fault then

**Comment by Explie** [comment]
delete now displays the returned data
