### ISSUE TITLE
'&' is not allowed on add fridgecontent but can be returned from eaninfo

### ISSUE THREAD

**Issue by Explie** [Explie/FridgeApp#95]
e.g.: 4003273217874

return on eaninfo
"name":"Baier & Schneider [...]"

on adding this product you get the error message: "Error Post body is not according to specifications"

**Comment by hftl-kalle** [comment]
using postman sending a product with a name containing '&' is certainly possible.
while debugging i noticed that when i used the app the post data of fridgeContent is undefined when entering '&'. please check again on your part

**Comment by Explie** [comment]
fixed by removing "&" from possible input chars. other possibility would be to re-implement the post-send code to encode the postdata before splitting it up, which is disproportionate for this bug
